title: ICYMI_GLAM 🤖
description: Inspired by @icymi_law@esq.social, the ICYMI_GLAM mastodon bot boosts things that are popular in libraryland.
author: Andromeda Yelton

theme: minima

base_url: /
repository: thatandromeda/mastodon_digest

github_username: thatandromeda
