title: ICYMI_GLAM 🤖
description: Inspired by <a href="https://esq.social/@icymi_law">@icymi_law</a>, the ICYMI_GLAM mastodon bot boosts things that are popular in libraryland.
author: Andromeda Yelton

theme: minima

base_url: /
repository: thatandromeda/mastodon_digest

github_username: thatandromeda
